version: "3.7"

services:
  opsdroid:
    build: .
    image: chatops
    ports:
      - 8080:8080
    volumes:
      -  ./config:/chatops/
      -  ./skills:/chatops/skills/
    environment:
      GITLAB_API_ADDR: ${GITLAB_API_ADDR}
      GITLAB_TOKEN: ${GITLAB_TOKEN}
      GITLAB_PROJECT_ID: ${GITLAB_PROJECT_ID}
      GITLAB_BRANCH_NAME: ${GITLAB_BRANCH_NAME}
      GITLAB_CD_YAML_FILE: ${GITLAB_CD_YAML_FILE}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
    entrypoint: ["opsdroid", "start"]
