welcome-message: false

logging:
  # path: ~/.opsdroid/output.log
  level: info
  console: true

connectors:
  slack:
    bot-token: $SLACK_BOT_TOKEN
    socket-mode: true # defaul true. *
    app-token: $SLACK_APP_TOKEN # socket-mode needs to be true
    # bot-name: "opsdroid" # default "opsdroid" **
    icon-emoji: ":robot_face:" # default ":robot_face:" **
    default-room: "#test" # default "#general"
    start-thread: false # default false. if true, opsdroid will start a thread when replying to a message

skills:
  ping:
    path: /chatops/skills/ping.py
  gitlab:
    path: /chatops/skills/gitlab.py

# databases:
#   sqlite:
#     path: "/root/.config/opsdroid/messages.db"
